const repo={higher:"https://github.com/TaeYiHam/Higher-Education-Outcomes-Analysis",beauty:"https://github.com/TaeYiHam/Global-Beauty-Spending-Analysis",coke:"https://github.com/TaeYiHam/Coca-Pepsi-Stock-Sentiment-Analysis",spotify:"https://github.com/TaeYiHam/Spotify-Music-Graph-Analysis",happy:"https://github.com/TaeYiHam/World-Happiness-Analysis"};
const cases={
higher:`<div class="kicker">Case study · Ongoing · Fall 2026</div><h2>Higher Education Outcomes Analysis</h2><p class="summary">An ongoing capstone using institution-level College Scorecard data to examine relationships among completion, cost, financial aid, selectivity, student debt, and post-graduation earnings.</p><div class="casegrid"><div><h4>Question</h4><p>How are college costs, completion, Pell Grant participation, selectivity, and earnings related across U.S. institutions?</p></div><div><h4>What I did</h4><p>Reduced 3,308 raw variables to 14 focused variables across 6,273 institutions, assessed missingness, created exploratory views, ran pairwise correlations, and built preliminary linear regression models.</p></div><div><h4>Tools</h4><p>R · College Scorecard · EDA · Correlation · Linear Regression · Data Visualization</p></div><div><h4>Current status</h4><p>The completion model currently uses 1,618 complete observations and the earnings model 1,949. These models are preliminary and are being used to guide the next stage of the capstone; no causal claims are made.</p></div></div><div class="gallery"><figure><img src="assets/project-visual-1.svg"><figcaption>Current project snapshot based on the repository's documented dataset and workflow.</figcaption></figure></div><a class="gh" href="${repo.higher}" target="_blank" rel="noopener noreferrer">View GitHub ↗</a>`,
beauty:`<div class="kicker">Case study · Summer 2025</div><h2>Global Beauty Spending Analysis</h2><p class="summary">An interactive R Shiny project exploring how beauty spending varies with economic development, gender inequality, and female labor-force participation across 50 countries.</p><div class="casegrid"><div><h4>Question</h4><p>Do countries with similar levels of economic development and gender equality still differ in beauty spending, and what regional patterns appear?</p></div><div><h4>What I did</h4><p>Integrated country-level socioeconomic and beauty-spending data and built a Shiny dashboard with scatter plots, trend lines, Pearson correlations, box plots, regional filters, and a bubble-chart view.</p></div><div><h4>Tools</h4><p>R · Shiny · ggplot2 · dplyr · readr · viridis · ggrepel</p></div><div><h4>Result / insight</h4><p>Exploratory analysis suggested higher-income countries generally had higher beauty spending per capita, while lower-income countries often devoted a larger share of income to beauty spending. Regional differences remained visible. These are descriptive associations, not causal effects.</p></div></div><div class="gallery"><figure><img src="assets/project-visual-2.png"><figcaption>Visualization reproduced directly from the 50-country repository dataset: GDP per capita vs. beauty spending as a share of household income; point size represents female labor-force participation.</figcaption></figure></div><a class="gh" href="${repo.beauty}" target="_blank" rel="noopener noreferrer">View GitHub ↗</a>`,
coke:`<div class="kicker">Case study · Fall 2025</div><h2>Coca-Cola & Pepsi: Stock Price and Public Sentiment</h2><p class="summary">A project combining social-media sentiment and stock-price data to explore changes in public sentiment alongside market movements.</p><div class="casegrid"><div><h4>Work</h4><p>Data preparation, sentiment analysis, and visualizations comparing sentiment patterns with stock-price trends.</p></div><div><h4>Portfolio role</h4><p>This was one of my first projects using Python to connect text-based sentiment data with financial market data.</p></div></div><a class="gh" href="${repo.coke}" target="_blank" rel="noopener noreferrer">View GitHub ↗</a>`,
spotify:`<div class="kicker">Case study · Spring 2026</div><h2>Spotify Music Graph Analysis</h2><p class="summary">A group graph-database project that transformed a music dataset into a Neo4j knowledge graph and used Cypher to explore relationships among tracks, artists, albums, and genres.</p><div class="casegrid"><div><h4>Question</h4><p>How can a graph model make relationships in music data easier to explore than a flat table?</p></div><div><h4>What I did</h4><p>The project cleaned and restructured the source data with Python, organized track/artist/album/genre records, modeled PERFORMED_BY, BELONGS_TO, and HAS_GENRE relationships, and used seven Cypher query tasks to explore the graph.</p></div><div><h4>Tools</h4><p>Python · Neo4j · Cypher · CSV · Graph Database</p></div><div><h4>Result / insight</h4><p>The queries explored popular tracks, title keywords, specific artists, upbeat/happy tracks, average popularity by genre, and top-genre counts. Repeated runtime testing also highlighted practical issues around data cleaning and query performance.</p></div></div><div class="gallery"><figure><img src="assets/project-visual-3.svg"><figcaption>Query tasks and average runtimes documented in the original group presentation. Each query was run 10 times.</figcaption></figure></div><a class="gh" href="${repo.spotify}" target="_blank" rel="noopener noreferrer">View GitHub ↗</a>`,
happy:`<div class="kicker">Case study · Fall 2023</div><h2>World Happiness Factors</h2><p class="summary">An early statistics project examining how GDP, social support, healthy life expectancy, and generosity relate to national happiness scores.</p><div class="casegrid"><div><h4>Methods</h4><p>Pearson correlation, multiple linear regression, scatterplots, and regional comparison.</p></div><div><h4>Role in portfolio</h4><p>This was one of my earlier data projects and gave me experience with correlation, regression, and statistical visualization in R.</p></div></div><a class="gh" href="${repo.happy}" target="_blank" rel="noopener noreferrer">View GitHub ↗</a>`
};
function openCase(k){document.getElementById("case").innerHTML=cases[k];document.getElementById("modal").classList.add("show");document.body.style.overflow="hidden"}
function closeCase(){document.getElementById("modal").classList.remove("show");document.body.style.overflow=""}
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeCase()});
document.querySelectorAll('a[href^="#"]').forEach(link=>{
  link.addEventListener("click",e=>{
    const target=document.querySelector(link.getAttribute("href"));
    if(!target)return;
    e.preventDefault();
    target.scrollIntoView({behavior:"smooth"});
    history.replaceState(null,"",location.pathname+location.search);
  });
});
